# Generated by Django 4.1 on 2022-08-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocuenta',
            old_name='type_account',
            new_name='type_name',
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_commissions',
            field=models.FloatField(default=1, verbose_name='Porcentaje de comision (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_cc',
            field=models.IntegerField(default=1, verbose_name='Tarjetas de credito maximas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_dc',
            field=models.IntegerField(default=1, verbose_name='Tarjetas de debito maximas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_deposit',
            field=models.IntegerField(default=0, verbose_name='Depositos maximos sin previo aviso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_with',
            field=models.IntegerField(default=0, verbose_name='Retiro diario maximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_overdraft',
            field=models.FloatField(default=0, verbose_name='Descubierto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_savings_usd',
            field=models.BooleanField(default=False, verbose_name='Caja de ahorro en dolares'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
