# Generated by Django 4.1 on 2022-09-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='hora',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_commissions',
            field=models.FloatField(null=True, verbose_name='Porcentaje de comision (%)'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_max_cc',
            field=models.IntegerField(null=True, verbose_name='Tarjetas de credito maximas'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_max_check',
            field=models.IntegerField(null=True, verbose_name='Chequeras maximas'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_max_dc',
            field=models.IntegerField(null=True, verbose_name='Tarjetas de debito maximas'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_max_deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depositos maximos sin previo aviso'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_max_with',
            field=models.IntegerField(null=True, verbose_name='Retiro diario maximo'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_overdraft',
            field=models.FloatField(null=True, verbose_name='Descubierto'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_prestamos',
            field=models.FloatField(null=True, verbose_name='Prestamos pre aprobados'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='type_savings_usd',
            field=models.BooleanField(null=True, verbose_name='Caja de ahorro en dolares'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='account_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
