# Generated by Django 4.1 on 2022-09-01 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='customer_username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_commissions',
            field=models.FloatField(null=True, verbose_name='Porcentaje de comision (%)'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_cc',
            field=models.IntegerField(null=True, verbose_name='Tarjetas de credito maximas'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_check',
            field=models.IntegerField(null=True, verbose_name='Chequeras maximas'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_dc',
            field=models.IntegerField(null=True, verbose_name='Tarjetas de debito maximas'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Depositos maximos sin previo aviso'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_with',
            field=models.IntegerField(null=True, verbose_name='Retiro diario maximo'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_overdraft',
            field=models.FloatField(null=True, verbose_name='Descubierto'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_prestamos',
            field=models.FloatField(null=True, verbose_name='Prestamos pre aprobados'),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='type_savings_usd',
            field=models.BooleanField(null=True, verbose_name='Caja de ahorro en dolares'),
        ),
    ]
