# Generated by Django 4.1 on 2022-08-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_rename_type_account_tipocuenta_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuenta',
            name='type_max_check',
            field=models.IntegerField(null=True, verbose_name='Chequeras maximas'),
        ),
    ]
