# Generated by Django 4.1 on 2022-09-01 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cliente_customer_username_movimientos_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente'),
        ),
    ]
