# Generated by Django 4.1 on 2022-09-01 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_cuenta_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='hora',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='account_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente'),
        ),
    ]
