# Generated by Django 4.1 on 2022-08-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_tipocuenta_type_max_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_max_check',
            field=models.IntegerField(blank=True, default=0, verbose_name='Chequeras maximas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_max_deposit',
            field=models.IntegerField(blank=True, verbose_name='Depositos maximos sin previo aviso'),
        ),
    ]
