# Generated by Django 4.1 on 2022-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_cuenta_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocliente',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
