# Generated by Django 4.1 on 2022-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_tipocliente_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocliente',
            name='type_savings_usd',
            field=models.BooleanField(default=False, verbose_name='Caja de ahorro en dolares'),
        ),
    ]
