# Generated by Django 4.1 on 2022-08-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_tipocuenta_type_max_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuenta',
            name='type_prestamos',
            field=models.FloatField(default=100000, verbose_name='Prestamos pre aprobados'),
            preserve_default=False,
        ),
    ]
