# Generated by Django 4.1 on 2022-09-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_tipocliente_type_savings_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.tipocuenta'),
            preserve_default=False,
        ),
    ]
