# Generated by Django 4.1 on 2022-08-30 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_tipocuenta_type_prestamos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='account_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente'),
            preserve_default=False,
        ),
    ]
