# Generated by Django 4.1 on 2022-09-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_alter_cuenta_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocuenta',
            old_name='type_account',
            new_name='type_name',
        ),
    ]
