# Generated by Django 4.1 on 2022-08-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_movimientos_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
