# Generated by Django 4.1 on 2022-09-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_rename_type_account_tipocuenta_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
