# Generated by Django 4.1 on 2022-08-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_movimientos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
