# Generated by Django 4.1 on 2022-09-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_rename_customer_id_cuenta_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
