# Generated by Django 4.1 on 2022-08-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_movimientos_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='hora',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
