# Generated by Django 4.1 on 2022-09-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_alter_cliente_dob'),
        ('cuentas', '0009_alter_cuenta_account_type_and_more'),
    ]

    operations = [
    ]
