# Generated by Django 4.1 on 2022-08-30 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_remove_movimientos_hora_movimientos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente'),
        ),
    ]
