# Generated by Django 4.1 on 2022-08-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_alter_cuenta_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_dni',
            field=models.TextField(db_column='customer_DNI'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
