# Generated by Django 4.1 on 2022-09-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_alter_cliente_branch_id_alter_cliente_customer_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuenta',
            name='type_account',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_dni',
            field=models.TextField(db_column='customer_DNI', unique=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='account_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_commissions',
            field=models.FloatField(null=True, verbose_name='Porcentaje de comision (%)'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_max_cc',
            field=models.IntegerField(null=True, verbose_name='Tarjetas de credito maximas'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_max_check',
            field=models.IntegerField(null=True, verbose_name='Chequeras maximas'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_max_dc',
            field=models.IntegerField(null=True, verbose_name='Tarjetas de debito maximas'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_max_with',
            field=models.IntegerField(null=True, verbose_name='Retiro diario maximo'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_overdraft',
            field=models.FloatField(null=True, verbose_name='Descubierto'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_prestamos',
            field=models.FloatField(null=True, verbose_name='Prestamos pre aprobados'),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='type_savings_usd',
            field=models.BooleanField(null=True, verbose_name='Caja de ahorro en dolares'),
        ),
    ]
