# Generated by Django 4.1 on 2022-08-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasTarjeta',
            fields=[
                ('brand_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('type_brand', models.TextField()),
            ],
            options={
                'db_table': 'marcas_tarjeta',
                'managed': False,
            },
        ),
    ]
