# Generated by Django 4.1 on 2022-09-01 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasTarjeta',
            fields=[
                ('brand_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('type_brand', models.TextField()),
            ],
            options={
                'db_table': 'marcas_tarjeta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.TextField(blank=True, null=True, unique=True)),
                ('card_cvv', models.IntegerField()),
                ('card_gived', models.TextField(blank=True, null=True)),
                ('card_expiration', models.TextField(blank=True, null=True)),
                ('card_type', models.TextField(blank=True, null=True)),
                ('card_brand', models.ForeignKey(blank=True, db_column='card_brand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarjetas.marcastarjeta')),
                ('client', models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.cliente')),
            ],
            options={
                'db_table': 'Tarjeta',
                'managed': True,
            },
        ),
    ]
