# Generated by Django 4.1 on 2022-08-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.TextField(blank=True, null=True, unique=True)),
                ('card_cvv', models.IntegerField()),
                ('card_gived', models.TextField(blank=True, null=True)),
                ('card_expiration', models.TextField(blank=True, null=True)),
                ('card_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tarjeta',
                'managed': False,
            },
        ),
    ]
