# Generated by Django 4.1 on 2022-09-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True},
        ),
    ]
