# Generated by Django 4.1 on 2022-09-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_alter_cuenta_account_type_and_more'),
        ('prestamos', '0002_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente'),
        ),
    ]
