# Generated by Django 4.1 on 2022-09-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamo_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_date',
            field=models.DateField(max_length=9),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table=None,
        ),
    ]
